arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: true
tabWidth: 4
trailingComma: all

overrides:
  - files: "*.sol"
    options:
      tabWidth: 4
      singleQuote: false
